#compose版本
version: "3"


services:
  forestage:
#微服务镜像
    image: forestage-app:1.0
    container_name: forestage-app
    ports:
      - "7777:7777"
#数据卷
    volumes:
      - /app/forestage:/data/forestage
    networks:
      - blog_network
    depends_on:
      - redis
      - mysql
      - nginx

  backstage:
#微服务镜像
    image: backstage-app:1.0
    container_name: backstage-app
    ports:
      - "7778:7778"
#数据卷
    volumes:
      - /app/backstage-app:/data/backstage-app
    networks:
      - blog_network
    depends_on:
      - redis
      - mysql
      - nginx

#redis服务
  redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"
    volumes:
      - /app/redis/redis.conf:/etc/redis/redis.conf
      - /app/redis/data:/data
    networks:
      - blog_network
    command: redis-server /etc/redis/redis.conf

 #mysql服务
  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: 'Qazz2333.'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'yozuru_blog'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Qazz2333.'
    ports:
       - "3306:3306"
    volumes:
       - /app/mysql/db:/var/lib/mysql
       - /app/mysql/conf/my.cnf:/etc/my.cnf
       - /app/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - blog_network
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问

 #nginx服务
  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /app/nginx/html:/usr/share/nginx/html
      - /app/nginx/logs:/var/log/nginx
      - /app/nginx/conf:/etc/nginx
    networks:
      - blog_network



 #创建自定义网络
networks:
   blog_network: