spring:
  profiles:
    group:
      "dev": devDB,devMVC,devCache
    active: dev
  main:
    banner-mode: off


logging:
  level:
    root: info

oss:
  accessKey: Uo2PmhiUHzoerPzTm19ssMzebGr0BheLxgW4ogVd
  secretKey: S3_BVGL8-HRSBspDpSZWaSxsZqtQ9KlxHSVxTs3j
  bucket: yozuru-blog
  cdn: http://rninhqsaw.hb-bkt.clouddn.com